config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  concern :votable do
    member do
      post :vote
      delete :unvote
    end
  end

  devise_for :users
  root to: 'questions#index'

  resources :questions, concerns: [:votable], defaults: { votable: 'questions' } do
    resources :answers, shallow: true, concerns: [:votable], except: %i[index], defaults: { votable: 'answers' }
    patch 'select_best_answer', action: :set_best_answer, on: :member
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index
  resources :comments, only: :create
  resource :subscriptions, only: %i[create destroy]

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', foreign_key: 'best_answer_id', optional: true

  has_one :reward, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :subscribe_author

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe_author
    subscriptions.create(user: author)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  expose :question, find: ->(id){ Question.with_attached_files.find(id) },
         build: ->(question_params){ current_resource_owner&.questions&.new(question_params) }
  expose :questions, ->{ Question.all }
  expose :answer, ->{ Answer.new }

  load_and_authorize_resource

  def index
    render json: questions
  end

  def show
    render json: question
  end

  def create
    if question.save
      render json: question
    else
      head :unprocessable_entity
    end
  end

  def update
    if question.update(question_params)
      render json: question
    else
      render json: { errors: answer.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    question.destroy
    render json: question
  end

  private

  def question_params
    params.require(:question).permit(:title, :body,
                                     files: [],
                                     links_attributes: [:name, :url, :_destroy, :id],
                                     reward_attributes: [:name, :image] )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_gon_question, only: %i[show]

  after_action :publish_question, only: [:create]

  expose :question, find: ->(id){ Question.with_attached_files.find(id) },
         build: ->(question_params){ current_user&.questions&.new(question_params) }
  expose :questions, ->{ Question.all }
  expose :answer, ->{ Answer.new }
  expose :without_best, ->{ question.answers - [question.best_answer] }

  load_and_authorize_resource

  def new
    question.links.new
    question.reward = Reward.new(question_id: question)
  end

  def show
    answer.links.new
  end

  def create
    if question.save
      redirect_to question, notice: 'Your question successfully created!'
    else
      render :new
    end
  end

  def update
    flash.now[:notice] = 'Your question has been successfully updated!' if question.update(question_params)
  end

  def destroy
    question.destroy
    redirect_to questions_path, notice: 'Your question successfully deleted.'
  end

  def set_best_answer
    question.update(best_answer_id: params[:answer_id])
    question.reward&.update(user: Answer.find(params[:answer_id]).author)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body,
                                     files: [],
                                     links_attributes: [:name, :url, :_destroy, :id],
                                     reward_attributes: [:name, :image] )
  end

  def publish_question
    unless question.errors.any?
      ActionCable.server.broadcast(
        'questions',
        ApplicationController.render(
          partial: 'questions/question',
          locals: {
            question: question,
            current_user: current_user
            },
          )
      )
    end
  end

  def set_gon_question
    gon.question_id = question.id
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_inline_edit_form.html.slim
.errors
  = render 'shared/errors', resource: question

= form_with model: question, local: false, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  #Links
    = f.fields_for :links do |link|
      = render 'shared/link_fields', f: link
    .link
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

  p= f.submit 'Save'

app/views/questions/_question.html.slim
- unless question.errors.any?
  li.question
    link Title: #{link_to question.title, question_path(question)}
    div Text:  #{ question.body }

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path

-if current_user
  p= link_to 'Your rewards', rewards_path

ul.questions-list = render questions

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  .links
    = f.fields_for :links do |link|
      = render 'shared/link_fields', f: link
    .link
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

  p Reward:
  p
    = f.fields_for :reward do |reward|
      = render 'shared/reward_fields', f:reward

  p= f.submit 'Ask'

app/views/questions/set_best_answer.js.erb
$('.errors').html('<%= render 'shared/errors', resource: question %>')

<% unless question.errors.present? %>
  <% if question.best_answer %>
    bestAnswer = $('.best-answer');
    bestAnswer.find('.answer').remove();
    bestAnswer.append('<%= j render question.best_answer %>');
    $('.answers').html('<%= j render without_best %>')
  <% end %>
  $('.notice').text('<%= notice %>');
<% end %>

app/views/questions/show.html.slim
.question id = "question-#{question.id}"
  h1.question-title= question.title
  p.question-body= question.body

  = render 'shared/votes', resource: question

  - if question.files.attached?
    - question.files.each do |file|
      .question-file id = "file-#{file.id}"
        p= link_to file.filename.to_s, url_for(file)

        - if current_user && can?(:destroy, file)
          p= link_to 'Delete', file_path(id: file),
                  remote: true,
                  method: :delete

  = render 'shared/links', resource: question

  - if question.reward.present?
    p Reward:
    = render question.reward

  = render 'questions/inline_edit_form'

  - if current_user && can?(:destroy, question) && can?(:update, question)
    link= link_to 'Delete question', question_path(question), method: :delete
    link= link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: question.id }

  p
    - if can?(:create, question.subscriptions) && can?(:destroy, question.subscriptions)
      - if current_user.subscribe?(question)
        link= link_to 'Unsubscribe', subscriptions_path(id: current_user.subscribe(question)), method: :delete, remote: true
      - else
        link= link_to 'Subscribe',
                subscriptions_path(question_id: question),
                method: :post,
                remote: true

  = render 'shared/comments', resource: question, current_user: current_user

.best-answer
  -if question.best_answer
    = render question.best_answer
  end

p= 'Answers:'

.answers
  = render without_best

.answer-errors

.create-answer
  p= 'Create new answer:'

  = render 'answers/form'

app/views/questions/update.js.erb
$('.errors').html('<%= render 'shared/errors', resource: question %>')

<% unless question.errors.present? %>
  $('.question').html('<%= j render question.reload %>')
  $('.notice').text('<%= notice %>');
<% end %>