config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  concern :votable do
    member do
      post :vote
      delete :unvote
    end
  end

  devise_for :users
  root to: 'questions#index'

  resources :questions, concerns: [:votable], defaults: { votable: 'questions' } do
    resources :answers, shallow: true, concerns: [:votable], except: %i[index], defaults: { votable: 'answers' }
    patch 'select_best_answer', action: :set_best_answer, on: :member
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index
  resources :comments, only: :create
  resource :subscriptions, only: %i[create destroy]

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities
    can :create, [Question, Answer, Comment]
    can :update, [Question, Answer], author_id: user.id
    can :destroy, [Question, Answer, File], author_id: user.id
    can :set_best_answer, Question, author_id: user.id
    can :destroy, ActiveStorage::Attachment, { record: { author_id: user.id } }
    can :destroy, Link, { linkable: { author_id: user.id } }
    can :me, User, user_id: user.id

    can :vote, [Question, Answer] do |resource|
      !user.is_author?(resource)
    end
    can :unvote, [Question, Answer] do |resource|
      user.voted_for?(resource)
    end

    can :create, Subscription, user_id: user.id
    can :destroy, Subscription, user_id: user.id
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :author, class_name: 'User'

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  validates :body, presence: true

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  after_create :notify_subscribers
  before_destroy :unset_best_answer

  private

  def unset_best_answer
    question.update(best_answer_id: nil) if question.best_answer_id == id
  end

  def notify_subscribers
    AnswerNotificationJob.perform_later(self)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :commentable, polymorphic: true

  validates :text, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, url: true

  def is_gist?
    url.include?('gist.github.com')
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', foreign_key: 'best_answer_id', optional: true

  has_one :reward, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :subscribe_author

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe_author
    subscriptions.create(user: author)
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true

  has_one_attached :image

  validates :name, :image, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :rewards, dependent: :destroy
  has_many :questions, dependent: :destroy, foreign_key: 'author_id'
  has_many :answers, dependent: :destroy, foreign_key: 'author_id'
  has_many :votes, dependent: :destroy, foreign_key: 'author_id'
  has_many :comments, dependent: :destroy, foreign_key: 'author_id'
  has_many :subscriptions, dependent: :destroy

  def is_author?(resource)
    resource.author_id == id
  end

  def vote(resource)
    votes.find_by(votable: resource)
  end

  def voted_for?(resource)
    vote(resource).present?
  end

  def subscribe(question)
    subscriptions.find_by(question_id: question.id)
  end

  def subscribe?(question)
    subscribe(question).present?
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :votable, polymorphic: true

  validates :up, inclusion: { in: [ -1, 1 ] }
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :authenticate_user!

  expose :file, find: ->(id){ ActiveStorage::Attachment.find(id) }

  authorize_resource

  def destroy
    file.purge
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!

  expose :link, ->{ Link.find(params[:id]) }

  load_and_authorize_resource

  def destroy
    link.destroy
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= include_gon(:init => true) %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_comments.html.slim
.comment-errors

ul.comments
  = render resource.comments
- if current_user
  = render 'comments/form', resource: resource

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_header.html.slim
header.navbar
  = link_to "Qna", root_path
  nav
    p.navbar-right
    - if current_user.present?
      link = link_to "Sign out", destroy_user_session_path, method: :delete
    - else
      link = link_to "Sign in", new_user_session_path
      link = link_to "Sign up", new_user_registration_path
    end

app/views/shared/_link_fields.html.slim
.nested-fields
  p
    = f.label :name, 'Link name'
    = f.text_field :name
  p
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/shared/_links.html.slim
-if resource.links.present?
  .attached-links
    p Links:
    ul
      - resource.links.each do |link|
        - if link.persisted?
          .link id = "link-#{link.id}"
            - if link.is_gist?
              = javascript_include_tag("#{link.url}.js")
            - else
              li= link_to link.name, link.url, target: :blank
            - if current_user && can?(:destroy, link)
              p= link_to "Delete", link_path(link),
                      method: :delete,
                      remote: true

app/views/shared/_reward_fields.html.slim
.nested-fields
  p
    = f.label :name, 'Reward name'
    = f.text_field :name
  p
    = f.label :image
    = f.file_field :image, direct_upload: true

app/views/shared/_votes.html.slim
div class="#{resource.class.to_s.downcase}-voting"
  p= "Score: #{resource.score}"
  - if current_user && can?(:vote, resource)
    - if current_user && can?(:unvote, resource)
      link= link_to 'UP', polymorphic_path(resource, action: :vote, id: resource, up: 1), class: 'vote-link hidden', remote: true, method: :post
      link= link_to 'DOWN', polymorphic_path(resource, action: :vote, id: resource, up: -1), class: 'vote-link hidden', remote: true, method: :post
      link= link_to 'Cancel', polymorphic_path(resource, action: :unvote, id: resource), class: 'cancel-link', remote: true, method: :delete
    - else
      link= link_to 'UP', polymorphic_path(resource, action: :vote,id: resource, up: 1), class: 'vote-link', remote: true, method: :post
      link= link_to 'DOWN', polymorphic_path(resource, action: :vote,id: resource, up: -1), class: 'vote-link', remote: true, method: :post
      link= link_to 'Cancel', polymorphic_path(resource, action: :unvote, id: resource), class: 'cancel-link hidden', remote: true, method: :delete
  - else
    link= link_to 'UP', polymorphic_path(resource, action: :vote, id: resource, up: 1), class: 'vote-link hidden', remote: true, method: :post
    link= link_to 'DOWN', polymorphic_path(resource, action: :vote, id: resource, up: -1), class: 'vote-link hidden', remote: true, method: :post
    link= link_to 'Cancel', polymorphic_path(resource, action: :unvote, id: resource), class: 'cancel-link hidden', remote: true, method: :delete