config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  concern :votable do
    member do
      post :vote
      delete :unvote
    end
  end

  devise_for :users
  root to: 'questions#index'

  resources :questions, concerns: [:votable], defaults: { votable: 'questions' } do
    resources :answers, shallow: true, concerns: [:votable], except: %i[index], defaults: { votable: 'answers' }
    patch 'select_best_answer', action: :set_best_answer, on: :member
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index
  resources :comments, only: :create
  resource :subscriptions, only: %i[create destroy]

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :author, class_name: 'User'

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  validates :body, presence: true

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  after_create :notify_subscribers
  before_destroy :unset_best_answer

  private

  def unset_best_answer
    question.update(best_answer_id: nil) if question.best_answer_id == id
  end

  def notify_subscribers
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!

  after_action :publish_answer, only: [:create]

  load_and_authorize_resource

  expose :question
  expose :answer, find: ->(id){ Answer.with_attached_files.find(id) },
         build: ->(answer_params){ Answer.new(answer_params.merge(question: question, author: current_user)) }

  def create
    respond_to do |format|
      if answer.save
        format.json { render json: answer }
      else
        format.json { render json: answer.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def update
    flash.now[:notice] = 'Your answer has been successfully updated!' if answer.update(answer_params)
  end

  def destroy
    answer.destroy
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :_destroy, :id])
  end

  def publish_answer
    unless answer.errors.any?
      rendered_answer = ApplicationController.render(
        partial: 'answers/answer',
        locals: {
          answer: answer,
          current_user: current_user,
          question: question
        })

      ActionCable.server.broadcast("question-#{question.id}",
                                   {
                                     answer: rendered_answer,
                                     answer_id: answer.id,
                                     answer_author_id: answer.author.id,
                                     question_author_id: question.author.id
                                   })
    end
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  expose :question
  expose :answer, find: ->(id){ Answer.with_attached_files.find(id) },
         build: ->(answer_params){ Answer.new(answer_params.merge(question: question, author: current_resource_owner)) }

  load_and_authorize_resource

  def index
    render json: question.answers
  end

  def show
    render json: answer
  end

  def create
      if answer.save
        render json: answer
      else
        render json: answer.errors.full_messages, status: :unprocessable_entity
      end
  end

  def update
    if answer.update(answer_params)
      render json: answer
    else
      render json: answer.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    answer.destroy
    render json: answer
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :_destroy, :id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer id = "answer-#{answer.id}"
  p= answer.body

  - if answer.files.attached?
    - answer.files.each do |file|
      .answer-file id = "file-#{file.id}"
        p= link_to file.filename.to_s, url_for(file)

        - if current_user && can?(:destroy, file)
          p= link_to 'Delete', file_path(id: file),
                  remote: true,
                  method: :delete

  =render 'shared/links', resource: answer

  .errors
    = render 'shared/errors', resource: answer

  - if current_user && can?(:destroy, answer) && can?(:update, answer)
    link= link_to 'Delete answer', answer_path(answer), class: 'optional-link', remote: true, method: :delete
    link= link_to 'Edit answer', '#', class: 'optional-link edit-answer-link', data: { answer_id: answer.id }

  - if current_user && can?(:select_best_answer, answer.question) && (answer != answer.question.best_answer)
    link= link_to 'Select best',
            select_best_answer_question_path(id: question, answer_id: answer.id),
            class: 'optional-link select-best-link',
            remote: true,
            method: :patch

  = render 'shared/votes', resource: answer, current_user: current_user

  = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
    p
      = f.label :body, 'Your answer'
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
    p Links:
    #Links
      = f.fields_for :links do |link|
        = render 'shared/link_fields', f: link
      .link
        = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

    p= f.submit 'Save', patch: :update

  = render 'shared/comments', resource: answer, current_user: current_user

app/views/answers/_form.html.slim
= form_with model: [question, answer], local: false, remote: true, class: 'new-answer', data: { type: :json } do |f|
  p
    = f.label :body
    = f.text_area :body

  p
    = f.label :files
    = f.file_field :files, class: 'new-answer-files', multiple: true, direct_upload: true

  p Links:
  #Links
    = f.fields_for :links do |link|
      = render 'shared/link_fields', f: link
    .link
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

  p= f.submit

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% if answer.persisted? %>
  $('.answers').append('<%= j render answer %>');
  $('.notice').text('<%= notice %>');
  $('.new-answer #answer_body').val('');
  fileForm = $('.new-answer-files #answer_files');
  fileForm.val('');
  fileForm.prop('disabled', false);
<% end %>

app/views/answers/destroy.js.erb
<% if answer.present? %>
  $('#answer-<%= answer.id %>').remove();
  $('.notice').text('<%= notice %>');
<% end %>

app/views/answers/update.js.erb
$('#answer-<%= answer.id %>').find('.errors').html('<%= render 'shared/errors', resource: answer %>')

<% unless answer.errors.present? %>
  $('#answer-<%= answer.id %>').html('<%= j render answer %>')
  $('.notice').text('<%= notice %>');
<% end %>